### PR TITLE
For hacktoberfest issue#19

### PR DESCRIPTION
**Pull request by rayoriz**
Commented all instances of ->logger across files

### CODE REVIEW

**Comment by concept-core** [comment]
Just delete those instances, if someone ever might think they want to use it they can.

**Comment by rayoriz** [comment]
Deleted all instances now!

**Comment by concept-core** [comment]
@rayoriz normally when I delete stuff I also delete extra whitelines and stuff that is not needed.
It's something I actually miss.

Can you fix that too ?

**Comment by rayoriz** [comment]
Cool. Deleted whitelines and also some deadcode now.

**Pull request merged**
